name: Run Tests

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to macos-latest or windows-latest if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version (use the one that fits your project)

    - name: Install dependencies
      run: |
        yarn install 

    - name: Run tests
      run: |
        yarn test
